services:
  hangfire-extension:
    build:
      context: .
      dockerfile: src/Hangfire.Extension.Web/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./artifacts/logs:/app/logs
